language: python
sudo: required
python:
  - "3.4"
addons:
  apt:
    packages:
    - libpcap-dev
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py install
  - pip install coveralls  
# command to run tests
script:
  - python setup.py test
  - coverage run --source=src/netzob setup.py test
after_success:
  - coveralls

